name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flet
        run: |
          pip install flet

      - name: Build APK
        run: |
          # Убираем возможные ошибки прав доступа
          flet build apk --no-docker --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-bundle
          path: build/apk/*.apk
